# Generated by Django 5.0.1 on 2024-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default=200, max_length=1000),
            preserve_default=False,
        ),
    ]
