# Generated by Django 5.0.1 on 2024-01-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_genres_favourites_alter_movies_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='genre_name',
        ),
    ]
