# Generated by Django 5.0.1 on 2024-01-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rename_name_genres_genre_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='genre_id',
        ),
    ]
