# Generated by Django 5.0.1 on 2024-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_movies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='genre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
