# Generated by Django 5.0.1 on 2024-01-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_genres_genre_id_movies_name_alter_genres_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre_name',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
