# Generated by Django 5.0.1 on 2024-01-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_movies_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='genre_id',
        ),
    ]
