# Generated by Django 5.0.1 on 2024-01-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_remove_favourites_genre_remove_favourites_movie_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
