# Generated by Django 5.0.1 on 2024-01-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_genres_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.genres'),
        ),
    ]
