# Generated by Django 5.0.1 on 2024-01-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='genre',
            new_name='genres',
        ),
    ]
