# Generated by Django 5.0.1 on 2024-01-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_rename_genre_favourites_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='movie_description',
        ),
        migrations.AddField(
            model_name='favourites',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='favourite_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.favourites'),
        ),
    ]
