# Generated by Django 5.0.1 on 2024-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_remove_favourites_status_favourites_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='status',
        ),
        migrations.AddField(
            model_name='favourites',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
