# Generated by Django 5.0.1 on 2024-01-31 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0022_rename_viewer_favourites_user_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='movies',
            name='favourite_status',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.favourites'),
        ),
    ]
