# Generated by Django 5.0.1 on 2024-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_alter_movies_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='created',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='status',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='genre_name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='favourite_status',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre_name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='name',
        ),
    ]
