# Generated by Django 5.0.1 on 2024-02-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_viewer_alter_movies_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('staatus', models.BooleanField(choices=[(True, 'favourite'), (False, 'not favourite')], default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.AddField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.genres'),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='F_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewer',
            name='L_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='favouritemovies',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movies'),
        ),
        migrations.AddField(
            model_name='favouritemovies',
            name='viewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.viewer'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='favourites',
            field=models.ManyToManyField(through='cinema.FavouriteMovies', to='cinema.movies'),
        ),
        migrations.AlterUniqueTogether(
            name='favouritemovies',
            unique_together={('viewer', 'movie')},
        ),
    ]
