# Generated by Django 5.0.1 on 2024-02-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0027_favouritemovies_delete_favourites_genres_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteMovies',
            new_name='FavouriteMovie',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
