# Generated by Django 5.0.1 on 2024-02-01 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_rename_favouritemovies_favouritemovie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='F_name',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='L_name',
        ),
        migrations.AddField(
            model_name='viewer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
