# Generated by Django 5.0.1 on 2024-02-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0029_remove_viewer_f_name_remove_viewer_l_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='user',
        ),
        migrations.AddField(
            model_name='viewer',
            name='F_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewer',
            name='L_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
