# Generated by Django 5.0.1 on 2024-02-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0034_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(choices=[(True, 'favourite'), (False, 'not favourite')], default=False)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='viewer',
            name='favourites',
            field=models.ManyToManyField(through='cinema.FavouriteMovie', to='cinema.movie'),
        ),
    ]
