# Generated by Django 5.0.1 on 2024-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0035_favouritemovie_viewer_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(null=True, to='cinema.genre'),
        ),
    ]
