# Generated by Django 4.2.3 on 2024-02-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0037_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='F_name',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='favourites',
        ),
        migrations.DeleteModel(
            name='FavouriteMovie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
