# Generated by Django 4.2.3 on 2024-02-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0038_remove_movie_genre_remove_viewer_f_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(choices=[(True, 'favourite'), (False, 'not favourite')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('favourited_movie', models.ManyToManyField(related_name='favourites', to='cinema.favouritemovie')),
                ('genre', models.ManyToManyField(to='cinema.genre')),
            ],
        ),
        migrations.AddField(
            model_name='favouritemovie',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
    ]
