# Generated by Django 5.0.2 on 2024-02-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0039_favouritemovie_movie_favouritemovie_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_name', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('viewer_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('F_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_favourite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.favouritemovie')),
            ],
        ),
    ]
