# Generated by Django 5.0.2 on 2024-02-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0040_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritemovie',
            name='owned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.viewer'),
        ),
    ]
