# Generated by Django 5.0.2 on 2024-02-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0041_favouritemovie_owned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritemovie',
            unique_together={('owned', 'movie')},
        ),
    ]
