# Generated by Django 5.0.2 on 2024-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0042_alter_favouritemovie_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='favourited_movie',
            field=models.ManyToManyField(null=True, related_name='favourites', to='cinema.favouritemovie'),
        ),
    ]
