# Generated by Django 5.0.2 on 2024-02-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0043_alter_movie_favourited_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favourited_movie',
        ),
    ]
