# Generated by Django 5.0.2 on 2024-02-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0044_remove_movie_favourited_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='is_favourite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
    ]
