# Generated by Django 5.0.2 on 2024-02-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0046_alter_viewer_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='is_favourite',
        ),
    ]
