# Generated by Django 5.0.2 on 2024-02-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0047_remove_viewer_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='is_favourite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.movie'),
        ),
    ]
