# Generated by Django 5.0.2 on 2024-02-11 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0048_viewer_is_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewer',
            unique_together={('F_name', 'is_favourite')},
        ),
    ]
