# Generated by Django 5.0.2 on 2024-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0049_alter_viewer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='cinema.genre'),
        ),
    ]
